package edu.uclm.esi.videochat;

// Generated by Selenium IDE

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.stereotype.Component;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import edu.uclm.esi.videochat.model.User;
import edu.uclm.esi.videochat.springdao.UserRepository;

import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;

import org.openqa.selenium.Keys;
import java.util.*;
import java.util.concurrent.TimeUnit;
import java.net.MalformedURLException;
import java.net.URL;

@RunWith (SpringJUnit4ClassRunner.class)
@SpringBootTest
public class LoginTest {
	private WebDriver chrome, firefox;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	@Autowired
	UserRepository usersRepo;

	@Before
	public void setUp() {
		System.setProperty("webdriver.chrome.driver", "D:\\Descargas\\chromedriver.exe");
		//System.setProperty("webdriver.gecko.driver", "C:\\Users\\monic\\Downloads\\geckodriver.exe");
		
		ChromeOptions options = new ChromeOptions();
		options.addArguments("use-fake-ui-for-media-stream");
	
		chrome = new ChromeDriver(options);
		//firefox = new FirefoxDriver();

		chrome.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		//chrome.quit();
	}
	
	

//	@Test
//	public void conversacion() {
//		hacerLogin(chrome, "pepe", "pepe");
//		hacerLogin(firefox, "monica", "monica");
//		
//		try {Thread.sleep(1000);} catch (InterruptedException e) {}
//		
//		chrome.findElement(By.linkText("Monica")).click();
//		String mensaje = "Hola, Monica";
//		chrome.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[2]/div/input")).sendKeys(mensaje);
//		chrome.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div/div[1]/div[2]/div/button[1]/span")).click();
//		
//		try {
//			Thread.sleep(1000);
//		} catch (InterruptedException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//		
//		String body = firefox.findElement(By.tagName("body")).getText();
//		assertTrue(body.contains(mensaje));
//	}
	
	@Test
	public void login() {
		hacerLogin(chrome, "Pepe", "pepe", 1);
		String a = "window.open('https://localhost:7500');";
		((JavascriptExecutor)chrome).executeScript(a);
		((JavascriptExecutor)chrome).executeScript(a);
		
	    ArrayList<String> tabs = new ArrayList<String> (chrome.getWindowHandles());
	    
	    chrome.switchTo().window(tabs.get(1)); 
	    hacerLogin(chrome, "Ana", "ana", 2);

	    chrome.switchTo().window(tabs.get(2)); 
	    
	    hacerLogin(chrome, "Lucas", "lucas", 2);
	    
	    chrome.switchTo().window(tabs.get(0));
	    
	    llamaryrechazar(chrome, tabs);
	    
	    llamaryaceptar(chrome, tabs);
	    
	}

	private void llamaryaceptar(WebDriver driver, ArrayList<String> tabs) {
		driver.switchTo().window(tabs.get(1));
		WebElement llamarAnaLucas = driver.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div[3]/div[1]/div[3]/button"));
		llamarAnaLucas.click();

		try {
			Thread.sleep(1000);
		}catch(InterruptedException e) {
			e.printStackTrace();
		}
		driver.switchTo().window(tabs.get(2));
		WebElement btnAceptarAAna = driver.findElement(By.xpath("//*[@id=\"btnAceptar\"]"));
		btnAceptarAAna.click();	
	    
}

	private void llamaryrechazar(WebDriver driver, ArrayList<String> tabs) {
		WebElement llamarPepeAna = driver.findElement(By.xpath("//*[@id=\"globalBody\"]/oj-module/div[1]/div[2]/div/div/div[3]/div[1]/div[2]/button"));
		llamarPepeAna.click();
		driver.switchTo().window(tabs.get(1));
		WebElement btnRechazarAPepe = driver.findElement(By.xpath("//*[@id=\"btnCortar\"]"));
		btnRechazarAPepe.click();
		driver.switchTo().window(tabs.get(0));
		
		try {
			Thread.sleep(2000);
		}catch(InterruptedException e) {
			e.printStackTrace();
		}
		
		
		assertThat(chrome.switchTo().alert().getText(), is("Llamada rechazada"));
		chrome.switchTo().alert().accept();
		
		
	    
}
	private void hacerLogin(WebDriver driver, String nombre, String pwd, int n) {

		
		 
		 if (driver instanceof ChromeDriver && n == 1) {
			 driver.get("https://localhost:7500/");
			 driver.findElement(By.id("details-button")).click();
			 driver.findElement(By.id("proceed-link")).click();
		 }
		 
		 try {
		  Thread.sleep(2000);
		 } catch (InterruptedException e) {
		  e.printStackTrace();
		 }

		 WebElement cajaNombre = driver.findElement(By.id("inputNombre"));
		 WebElement cajaPwd = driver.findElement(By.id("inputPwd"));
		 WebElement btnEntrar = driver.findElement(By.id("btnEntrar"));
		 cajaNombre.click();
		 cajaNombre.sendKeys(nombre);
		 cajaPwd.click();
		 cajaPwd.sendKeys(pwd);
		 btnEntrar.click();
		 try {
		  Thread.sleep(500);
		 } catch (InterruptedException e) {
		  e.printStackTrace();
		 }
		 assertThat(driver.findElement(By.id("Chat")).getText(), is("Fantastico videochat"));
		 try {
		  Thread.sleep(500);
		 } catch (InterruptedException e) {
		  e.printStackTrace();
		 }
		}

	//@Test
	public void registro(){
	    Optional<User> optUserPepe = usersRepo.findByName("Pepe");
	    if (optUserPepe.isPresent()){
	        User user = optUserPepe.get();
	        usersRepo.deleteById(user.getId());
	    }
	    Optional<User> optUserAna = usersRepo.findByName("Ana");
	    if (optUserAna.isPresent()){
	        User user = optUserAna.get();
	        usersRepo.deleteById(user.getId());
	    }
	    Optional<User> optUserLucas = usersRepo.findByName("Lucas");
	    if (optUserLucas.isPresent()){
	        User user = optUserLucas.get();
	        usersRepo.deleteById(user.getId());
	    }

	    registrar(chrome, "Pepe", "pepe@gmail.com", "pepe",
	    "C:\\Users\\Ismael\\Desktop\\1.jpg");

	    try {
	        Thread.sleep(500);
	    } catch (InterruptedException e) {
	        e.printStackTrace();
	    }

	    registrar(chrome, "Ana", "ana@gmail.com", "ana",
	    "C:\\Users\\Ismael\\Desktop\\1.jpg");

	    try {
	        Thread.sleep(500);
	    } catch (InterruptedException e) {
	        e.printStackTrace();
	    }

	    registrar(chrome, "Lucas", "lucas@gmail.com", "lucas",
	    "C:\\Users\\Ismael\\Desktop\\1.jpg");
	}
	
	private void registrar(WebDriver drive, String nombre, String email, String pwd, String urlFoto) {
		drive.get("https://localhost:7500/");
		
		try {
			Thread.sleep(500);
		}catch(InterruptedException e) {
			e.printStackTrace();
		}
		
		WebElement link = drive.findElement(By.linkText("Crear cuenta"));
		link.click();
		WebElement cajaNombre= drive.findElement(By.id("nombre"));
		WebElement cajaEmail= drive.findElement(By.id("email"));
		WebElement cajaPwd1= drive.findElement(By.id("pwd1"));
		WebElement cajaPwd2= drive.findElement(By.id("pwd2"));
		WebElement seleccionArchivo= drive.findElement(By.id("img"));
		WebElement boton= drive.findElement(By.id("btnCrearCuenta"));

		cajaNombre.click();
		cajaNombre.sendKeys(nombre);

		cajaEmail.click();
		cajaEmail.sendKeys(email);

		cajaPwd1.click();
		cajaPwd1.sendKeys(pwd);

		cajaPwd2.click();
		cajaPwd2.sendKeys(pwd);

		//seleccionArchivo.sendKeys(urlFoto);
		boton.click();
		
		try {
			Thread.sleep(2000);
		}catch(InterruptedException e) {
			e.printStackTrace();
		}
		
		assertThat(chrome.switchTo().alert().getText(), is("Registrado correctamente"));
		chrome.switchTo().alert().accept();

		
	}
	
	
}
